/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { rootRoute } from './routes/__root'

// Create and export the route tree

export const routeTree = rootRoute.addChildren([])

/* prettier-ignore-end */
